name: manual_reorderable_list
description: "Reorderable list with possible manual triggering of reordering"
version: 1.0.0
homepage: https://github.com/crefter/app_onboarding
repository: https://github.com/crefter/app_onboarding
issue_tracker: https://github.com/crefter/app_onboarding/issues

environment:
  sdk: ">=3.0.0 < 4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: